name: Hello
on: push
env:
  SECRET_HOGE_1: ${{secrets.BASE_URL}} ## ※1
jobs:
  hello:
    runs-on: ubuntu-latest
    name: Hello
    steps:
      - name: Test
        env:
          TEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          echo ${#TEST_GITHUB_TOKEN}
          echo ${#BASE_URL}
